export const SUCCESSFULL_REGISTRATION = "SUCCESSFULL_REGISTRATION";
export const ERROR_REGISTRATION = "ERROR_REGISTRATION";
export const GET_USER = "GET_USER";
export const SUCCESSFULL_LOGIN = "SUCCESSFULL_LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const LOG_OUT = "LOG_OUT";
